### PR TITLE
chore(header): user personal token

### PR DESCRIPTION
**Pull request by appleboy**
ref: https://github.com/essentialkaos/go-confluence/pull/52

some code has been reverted?

Please help to review. See https://github.com/appleboy/go-confluence/commit/9072af36d1c1a008c08a274c360568ea42e379b9#diff-f094be01394bad772f752858808afe0ebc4a8db693b4e40be69e3162f7257f1fL975

### CODE REVIEW

**Comment by andyone** [comment]
Hi! Yes, it was reverted. I didn't notice that the previous PR was made to the master branch. It's allowed by our release process with separate PRs for releases. 

I applied a diff from PR #52 and it doesn't have code from this PR because you have removed it as part of b2439bfcc19017cf7d20f0ca93a19895547c893b. This is the reason why this code is not presented in the release.

**Comment by appleboy** [comment]
@andyone Thanks for your response quickly.

**Comment by andyone** [comment]
@appleboy I have release [5.2.1](https://kaos.sh/go-confluence/r/v5.2.1) with this fix.

**Comment by appleboy** [comment]
@andyone Thanks.

**Pull request merged**
